### ISSUE TITLE
@media print CSS

### ISSUE THREAD

**Issue by tresf** [qzind/tray#55]
Migrated from https://github.com/qzind/qz-print/issues/190.

---

@vt09 wrote: 

Currently, html content under @media print style still appear in rendered file.

For example, we have setting as below.

``` css
  /*HIGHLIGHT/NOTIFICATION PAGE DOESN'T NEED TO BE PRINTED*/
  @media print {
      #page0 {
          display:none;
      }
  }
```

... or 

From the mailing list:

``` css
@media print { .pagebreak {page-break-after: always;}}
```

``` html
<div id="page0">
    <b style="font-size:40px;">Payment type of this order:</b>
    <h1>Cybersource_CreditCard</h1>
    <br/>
    <hr color="#000000" />
    <br/>
</div>
```

Do our printHTML support this style?
